### ISSUE TITLE
What are "the necessary gnome hooks" and "gnomeConfig" and how does one use it "properly" ?

### ISSUE THREAD

**Issue by phil-s** [Gekkio/gnome-session-xmonad#15]
The instructions say:

> Your xmonad configuration must have the necessary gnome hooks in place. In practice things work perfectly if you are using gnomeConfig properly in your configuration.

There is no indication as to what any of that means, how one might establish whether it is the case, or where to begin if it is not.  It's not too far from saying "Your xmonad configuration must contain mystery code."

Perhaps you could link to some documentation for "gnomeConfig" which explains how to use it?

**Comment by srstevenson** [comment]
This is documented [on Hackage](https://hackage.haskell.org/package/xmonad-contrib-0.10/docs/XMonad-Config-Gnome.html), which I agree would be good to link to from the README. You can get up and running by populating `~/.xmonad/xmonad.hs` with:

```haskell
import XMonad
import XMonad.Config.Gnome

main = xmonad gnomeConfig
```

and running `xmonad --recompile` from a shell.
