### ISSUE TITLE
xenial support

### ISSUE THREAD

**Issue by schuyler1d** [Gekkio/gnome-session-xmonad#2]
Not sure if this is the right place, but after installing xenial (16.04) the Gnome Flashback+Xmonad session would just die when starting.

I was able to 'fix' this by changing /usr/share/gnome-session/sessions/gnome-flashback-xmonad.session
replacing 'gnome-settings-daemon' with 'unity-settings-daemon'.  It seems gnome-settings-daemon doesn't exist anymore (or doesn't with just gnome-session-flashback and xmonad installed.

Insofar, as it seems like these files are downstream of your work -- THANK YOU!  I'm so grateful that you've made xmonad useable in Ubuntu over the years.

**Comment by Gekkio** [comment]
It's super confusing, but this is not actually the repository for that session.
This repository is for the package gnome-session-xmonad, which is available in my PPA repository.
The one you are talking about is maintained in the Debian xmonad package, which has a history of being broken in Ubuntu and the gnome session was even removed recently. It was re-added in Xenial, but just like you observed, it doesn't work! The brokenness on Ubuntu led me to create and maintain this package. I support all active Ubuntu versions, including Xenial.
