### ISSUE TITLE
Depedencies from the xmonad package (question)

### ISSUE THREAD

**Issue by asr** [Gekkio/gnome-session-xmonad#7]
I need to install `gnome-session-xmonad` without installing the `xmonad` package shipped with Ubuntu. Besides the `xmonad` executable what else needs `gnome-session-xmonad` from the `xmonad` package?

**Comment by Gekkio** [comment]
I don't think anything else is needed from that package, but remember to also install the ghc libraries (= `libghc-xmonad-dev`, `libghc-xmonad-contrib-dev`) to use custom configuration files.

**Comment by asr** [comment]
I don't know why but the file

```
/usr/share/applications/xmonad.desktop
```

is also needed. I'll continue testing, if I found more needed files, I'll report them here.
