### ISSUE TITLE
Ubuntu 17.04 logs out after 1min 30sec

### ISSUE THREAD

**Issue by casutherland** [Gekkio/gnome-session-xmonad#8]
Select "GNOME + XMonad" or "GNOME Flashback (Xmonad)" sessions from GDM and the user is automatically logged out after 1min 30sec with the following error in kern.log:

**gnome-session-binary[1965]: Unrecoverable failure in required component xmonad.desktop**

From /var/log/kern.log
```
    Oct 16 00:57:28 kingpin indicator-sound[934]: g_object_ref: assertion 'object->ref_count > 0' failed
    Oct 16 01:00:27 kingpin indicator-sound[1945]: volume-control-pulse.vala:735: unable to get pulse unix socket: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.PulseAudio1 was not provided by any .service files
    Oct 16 01:00:27 kingpin gnome-screensav[1997]: Couldn't get presence status: The name org.gnome.SessionManager was not provided by any .service files
    Oct 16 01:00:27 kingpin gsd-sharing[2074]: Failed to StopUnit service: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit rygel.service not loaded.
    Oct 16 01:00:39 kingpin gnome-terminal-[2226]: Allocating size to GtkBox 0x55a3d3297880 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
    ...
    Oct 16 01:01:58 kingpin gnome-session-binary[1965]: Unrecoverable failure in required component xmonad.desktop
```

**Comment by Gekkio** [comment]
Hmm, maybe xmonad is not registering itself as the window manager properly. What does your `xmonad.hs` look like?

**Comment by casutherland** [comment]
Just added the basics, just now.

```
$ cat ~/.xmonad/xmonad.hs
import XMonad
import XMonad.Config.Gnome

main = xmonad gnomeConfig
```

Now I'm seeing a gnome panel show up, for a second or two, then logout back to the GDM greeter.

From /var/log/kern.log
```
Oct 16 02:56:13 kingpin kernel: [  218.274197] gnome-flashback[2936]: segfault at 40 ip 000055e93e742bf0 sp 00007ffeab93b268 error 4 in gnome-flashback[55e93e714000+9d000]
Oct 16 02:56:15 kingpin kernel: [  219.543121] gnome-flashback[2951]: segfault at 40 ip 00005566e7ad9bf0 sp 00007ffd7ffd0798 error 4 in gnome-flashback[5566e7aab000+9d000]
```

**Comment by Gekkio** [comment]
Could you try logging in with a session type called "GNOME Flashback (Metacity)"? Since gnome-flashback is crashing, I'd like to first confirm that a normal session without xmonad works fine. I've hit some GNOME bugs in 17.04 myself...

**Comment by casutherland** [comment]
Other sessions are (+) working, however all of the "GNOME Flashback" sessions, including "GNOME + XMonad" are (-) failing with immediate segfaults. [1]

```
+ awesome
+ GNOME Classic
+ GNOME
- GNOME Flashback (Compiz)
- GNOME Flashback (Metacity)
- GNOME Flashback (Xmonad)
- GNOME + XMonad
+ Ubuntu
+ XMonad
```

[1] From /var/log/kern.log:
```
Oct 20 20:59:03 kingpin kernel: [  706.814786] gnome-flashback[4179]: segfault at 40 ip 000055c48c062bf0 sp 00007ffc150957c8 error 4 in gnome-flashback[55c48c034000+9d000]
Oct 20 20:59:04 kingpin kernel: [  707.095057] gnome-flashback[4222]: segfault at 40 ip 000055728a15bbf0 sp 00007ffc475dc588 error 4 in gnome-flashback[55728a12d000+9d000]
```

Thank you Gekkio. Appreciate the recommendations here. I'll continue trying to dig a little deeper.

**Comment by qcu** [comment]
Thank you Gekkio. Appreciate the recommendations here. I'll try to dig a little deeper into troubleshooting this myself.

**Comment by casutherland** [comment]
Upgraded to 17.10 and GNOME + XMonad is working now. Thanks.
