### ISSUE TITLE
E: The repository 'http://ppa.launchpad.net/gekkio/xmonad/ubuntu bionic Release' does not have a Release file.

### ISSUE THREAD

**Issue by mschaaf** [Gekkio/gnome-session-xmonad#9]
After adding the ppa:gekkio/xmonad to my system currently ubuntu 18.04 I get the following error message:

    E: The repository 'http://ppa.launchpad.net/gekkio/xmonad/ubuntu bionic Release' does not have a 
    Release file.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.

Would be nice if you could add support for it. Thanks.

**Comment by Gekkio** [comment]
Bionic 18.04 LTS is now supported :smile:

**Comment by mschaaf** [comment]
Thank you, it works now.
